##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile
##

all : 
	make -C ./generator/ all
	make -C ./solver/ all

clean :
	make -C ./generator/ clean
	make -C ./solver/ clean

fclean :
	make -C ./generator/ fclean
	make -C ./solver/ fclean

re :
	make -C ./generator/ re
	make -C ./solver/ re
